# Generated by Django 4.2.27 on 2026-01-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.PositiveIntegerField()),
                ('numero', models.CharField(max_length=100)),
                ('nascimento', models.CharField(max_length=200)),
                ('resumo', models.TextField()),
                ('foto', models.CharField(help_text='Nome do arquivo em app/static/blog/ (ex.: gi_hun.jpg)', max_length=255)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordenação na página.')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ator/Personagem',
                'verbose_name_plural': 'Atores/Personagens',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('info', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Início',
                'verbose_name_plural': 'Início',
            },
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('foto', models.CharField(blank=True, help_text='Nome do arquivo em app/static/blog/ (ex.: squid-game-round-6-temporada.jpg)', max_length=255)),
                ('legenda', models.CharField(blank=True, max_length=255)),
                ('info', models.TextField(blank=True)),
                ('criadores', models.CharField(blank=True, max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sobre',
                'verbose_name_plural': 'Sobre',
            },
        ),
    ]
